name: voice-to-text
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy=1.26.4
  - pip:
      - faster-whisper
      - pyaudiowpatch
      - soundfile
      - PyQt6
      - nvidia-cublas-cu12
      - nvidia-cudnn-cu12
      - opencc-python-reimplemented
